
import { Request, MockData } from './types';

const formatDateToYYYYMMDD = (date: Date): string => {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0'); // getMonth() is 0-indexed
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
};

export const getInitialRequestState = (): Request => {
    const today = new Date();
    const tomorrow = new Date(today);
    tomorrow.setDate(tomorrow.getDate() + 1);

    return {
        id: ``, // ID will be generated by Supabase
        solicitante: '', data_solicitacao: formatDateToYYYYMMDD(today),
        centro_custo: '', equipe_members: '', quant_equipe: 1,
        hotel_name: '', client_name: '',
        check_in: formatDateToYYYYMMDD(today), check_out: formatDateToYYYYMMDD(tomorrow),
        quant_diarias: 1, valor_diaria: 0, valor_total: 0,
        pix: '', cnpj: '', nf: '',
        nf_attachments: [], pix_attachments: [],
    };
};

export const INITIAL_MOCK_DATA: MockData = {
  clientes: [
    { id: 'client_1', cliente: 'CLIENTE ALPHA', cidade: 'SÃO PAULO', distancia: '100', lat_final: '-23.550520', lon_final: '-46.633308', searchableKeywords: ['cliente', 'alpha', 'são', 'paulo'] },
    { id: 'client_2', cliente: 'EMPRESA BETA', cidade: 'RIO DE JANEIRO', distancia: '450', lat_final: '-22.906847', lon_final: '-43.172897', searchableKeywords: ['empresa', 'beta', 'rio', 'de', 'janeiro'] }
  ],
  hoteis: [
    { id: 'hotel_1', client_id: 'client_1', hotel: 'HOTEL CENTRAL PARK', cnpj: '11222333000144', telefone: '11999998888', dados_pag: 'pix@central.com', quarto_ind: 150.00, quarto_dup: 250.00, quarto_tri: 320.00 },
    { id: 'hotel_2', client_id: 'client_2', hotel: 'ORLA COPACABANA HOTEL', cnpj: '44555666000177', telefone: '21988887777', dados_pag: 'pix@orla.com', quarto_ind: 200.00, quarto_dup: 350.00, quarto_tri: 450.00 }
  ],
  colaboradores: [
    { id: 'collab_1', nome: 'JOÃO DA SILVA', cpf: '111.222.333-44', data_nasc: '1990-01-15', pix: 'joao.silva@pix.com', banco: 'BANCO DO BRASIL', funcao: 'Técnico', filial: 'SP' },
    { id: 'collab_2', nome: 'MARIA OLIVEIRA', cpf: '555.666.777-88', data_nasc: '1995-05-20', pix: 'maria.o@pix.com', banco: 'ITAÚ', funcao: 'Motorista', filial: 'RJ' }
  ],
  solicitacoes: [],
  historico: [],
  rotas: [
    { id: 'rota_1', filial: 'SEDE SP', default_latitude: '-23.550520', default_longitude: '-46.633308', isDefault: true }
  ],
  stockItems: [
    { id: 'uniforme-camisa-polo-m', classe: 'UNIFORME', tipo: 'CAMISA POLO', tamanho: 'M', quantidade: 50 },
    { id: 'epi-capacete-unico', classe: 'EPI', tipo: 'CAPACETE', tamanho: 'ÚNICO', quantidade: 20 }
  ],
  stockHistory: [],
  stockPdfSettings: {
    id: 1, headerTitle: 'CONTROLE DE UNIFORMES E EPIS', branchName: 'SEDE SP', managerName: 'GERENTE GERAL', logoURL: ''
  },
  veiculos: [
    { id: 'vehicle_1', placa: 'ABC1D23', filial: 'SP', tipo: 'CARRO OPERACIONAL', modelo: 'FIAT STRADA', chassi: '9BD178378H8123456', ano: '2022', isLocado: false }
  ],
  diarias: [],
  diariaSettings: {
    id: 1, valor_diaria: 100, valor_pernoite: 150, valor_diaria_carreteiro: 120
  }
};
